blank_issues_enabled: false
contact_links:
  - name: 💬 Discord communautaire
    url: https://discord.gg/BmUHBf2bnm
    about: Aide rapide, entraide et discussions (FR)
  - name: 🌐 Site & carte interactive
    url: https://33immortals.fr
    about: Le site et la carte en ligne
