name: 💡 Feature request / Suggestion
description: Suggest an idea / Proposer une idée
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your idea / Ton idée
      description: What would you like added or improved? / Que voudrais-tu voir ajouté ou amélioré ?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why? / Pourquoi ?
      description: Why would it help? / En quoi est-ce utile ?
